### ISSUE TITLE
fix coveralls coverage reporting

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.impersonate#4]
Travis test run succeeds but errors on submitting test coverage report to coveralls.io at https://travis-ci.com/collective/collective.impersonate/builds/115695573#L1508

```
$ coveralls
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/coveralls/api.py", line 180, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by thet** [comment]
I removed the coverage report from buildout and travis. We have only very sparse tests, so it doesn't make much sense.
We can add coverage tests later when we have a proper test suite.

**Comment by solancer** [comment]
I was facing the same issue on Github actions, adding `--service=gihtub` in front of the coveralls command fixed it for me

```
name: Coveralls
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: coveralls --service=github
```
